# Generated by Django 4.2.1 on 2023-06-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_joining', models.DateTimeField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.base')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_price', models.IntegerField()),
                ('book_description', models.CharField(max_length=500)),
            ],
            bases=('mainapp.base',),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.base')),
                ('club_category', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('membership', models.IntegerField()),
            ],
            bases=('mainapp.base',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.base')),
                ('roll_number', models.IntegerField()),
                ('type_of_field', models.TextField()),
            ],
            bases=('mainapp.base',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.base')),
                ('salary', models.IntegerField()),
                ('teacher_dept', models.CharField(max_length=50)),
                ('teacher_qualification', models.CharField(max_length=50)),
            ],
            bases=('mainapp.base',),
        ),
    ]
