# Generated by Django 4.2.1 on 2023-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_mainadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainadmin',
            name='contactno',
        ),
        migrations.RemoveField(
            model_name='mainadmin',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='mainadmin',
            name='fullname',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mainadmin',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainadmin',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
