# Generated by Django 4.2.1 on 2023-06-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_base_date_of_birth_alter_base_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='date_of_birth',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='date_of_joining',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
